### ISSUE TITLE
The leader-key s-SPC doesn't show me the availabe keys

### ISSUE THREAD

**Issue by nhmacuk** [timor/spacemacsOS#11]
s-SPC-  which-key: There are no keys to show [2 times]
Do you know how I could be able to see the which-key for the s-SPC prefix?
Same for s-SPC s-SPC, which only shows me "M-x:" and not helm.

**Comment by timor** [comment]
Yes, that is a known issue at the moment.  The problem is that (at least until https://github.com/syl20bnr/spacemacs/pull/13363), having more than one leader key for which-key was not supported.  The hacks I tried resulted in inconsistent or buggy behavior.

It might make sense to look at this again, however, having `s-SPC` as an additional leader key is hacky in the first place...

with regards to the helm issue, I suspect that is something different.  I don't use helm, so I don't know how the `M-x` binding is put in place there.  May have to look at that...

**Comment by timor** [comment]
@nhmacuk To fix the second problem, could you try with 83b97b23?

**Comment by nhmacuk** [comment]
Hey thanks, it now works after pulling your latest commit! :)
